[package]
name = "osu-rust"
version = "0.1.0"
edition = "2021"
authors = ["xiaohuihuiold <xiaohuihuiold@gmail.com>"]
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
