[package]
name = "deserialize_derive"
version = "0.1.0"
edition = "2021"
authors = ["xiaohuihuiold <xiaohuihuiold@gmail.com>"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
syn = "1.0.99"
